import type { Address } from "viem";
import { resolveGoal, type GoalPreview, type GoalSpec, type ResolveContext } from "@sama/agent";
import type { ResidualStyle, Target, TargetPreview } from "@sama/api-types";
import type { ExecutionPolicy, Holding } from "@sama/portfolio";
import type { AssetUid } from "@sama/shared";
import { deps } from "./deps.ts";
import { InputError } from "./errors.ts";
import { displayPrices, loadPortfolio, tokensOf, usd, type LoadedPortfolio } from "./market.ts";
import type { SavedTarget } from "./users.ts";

/** The allowlist is a checked-in file regenerated by CI; a month-old file is still a valid universe. */
export const MAX_ALLOWLIST_AGE_SEC = 30 * 86_400;

export type TargetInput = Omit<Target, "savedAt">;

/** Whole basis points per symbol from the client's percent weights; rejects unknown symbols and totals other than 100%. */
export function normalizeTarget(input: TargetInput): Omit<SavedTarget, "updatedAt"> {
  if (!input || typeof input !== "object" || typeof input.weights !== "object" || input.weights === null) throw new InputError("Send weights as { SYMBOL: percent }.");
  const reg = deps().registry();
  const weights: SavedTarget["weights"] = [];
  let total = 0;
  for (const [symbol, pct] of Object.entries(input.weights)) {
    if (typeof pct !== "number" || !Number.isFinite(pct) || pct < 0 || pct > 100) throw new InputError(`${symbol}: weight must be between 0 and 100.`);
    const asset = reg.findSymbol(symbol);
    if (!asset) throw new InputError(`${symbol} is not an asset Sama trades.`);
    total += pct;
    const bps = Math.round(pct * 100);
    if (bps > 0) weights.push({ uid: asset.uid, symbol: asset.symbol, weightBps: bps });
  }
  if (Math.abs(total - 100) > 0.05) throw new InputError(`Weights add up to ${total.toFixed(1)}%, not 100%.`);
  // Rounding drift goes to the largest weight so the saved target sums to exactly 10,000 bps.
  const drift = 10_000 - weights.reduce((s, w) => s + w.weightBps, 0);
  if (drift !== 0 && weights.length) weights.reduce((a, b) => (b.weightBps > a.weightBps ? b : a)).weightBps += drift;
  const residualStyle: ResidualStyle = input.residualStyle ?? "ECONOMIC";
  if (!["ECONOMIC", "CARRY_FORWARD", "CANCEL"].includes(residualStyle)) throw new InputError(`Unknown residual style ${String(residualStyle)}.`);
  const costCapBps = input.costCapBps ?? 100;
  if (!Number.isInteger(costCapBps) || costCapBps < 0 || costCapBps > 2_000) throw new InputError("The cost cap must be a whole number of basis points between 0 and 2000.");
  return { weights: weights.sort((a, b) => b.weightBps - a.weightBps), costCapBps, residualStyle };
}

export function policyFor(target: Pick<SavedTarget, "costCapBps" | "residualStyle">, nowSec: number, roundDurationSec = 900): ExecutionPolicy {
  return {
    maxExternalSlippageBps: target.costCapBps,
    maxReferencePriceDriftBps: 100,
    maxRoundDurationSec: roundDurationSec,
    allowPartialCross: true,
    allowMarketResidual: target.residualStyle === "ECONOMIC",
    allowLimitResidual: false,
    allowTwapResidual: false,
    allowWaitResidual: target.residualStyle !== "CANCEL",
    urgency: "NORMAL",
    validUntil: nowSec + 3_600,
  };
}

/** Every saved weight, plus 0% for anything held but not named: a target describes the whole wallet. */
export function specFromTarget(target: Pick<SavedTarget, "weights">, heldSymbols: readonly string[]): GoalSpec {
  const named = new Set(target.weights.map((w) => w.symbol));
  const ops = [...target.weights.map((w) => ({ symbol: w.symbol, pct: w.weightBps / 100 })), ...heldSymbols.filter((s) => !named.has(s)).map((s) => ({ symbol: s, pct: 0 }))];
  return {
    operations: ops.map((o) => ({ op: "SET_WEIGHT" as const, symbol: o.symbol, weightPct: o.pct, from: null, to: null, fraction: null })),
    remainderTo: null,
    cashWeightPct: null,
    constraints: { maxExternalSlippageBps: null, allowMarketResidual: null, residualStyle: null, twapDurationSec: null, urgency: null, crossAsMuchAsPossible: true },
    circleName: null,
    roundTiming: null,
    clarificationsNeeded: [],
  };
}

/** Resolver context from a fresh server-side read of the wallet. Client-supplied balances are never used. */
export async function resolveContext(portfolio: Extract<LoadedPortfolio, { ok: true }>, overridePrices?: ReadonlyMap<AssetUid, bigint>): Promise<ResolveContext> {
  const reg = deps().registry();
  const prices = new Map<AssetUid, bigint>(await displayPrices());
  if (overridePrices) for (const [uid, p] of overridePrices) prices.set(uid, p);
  const holdings: Holding[] = portfolio.holdings.map((h) => ({ owner: portfolio.address, assetUid: h.asset.uid, token: h.asset.contractAddress, rawBalance: h.rawBalance }));
  return { owner: portfolio.address, holdings, registry: reg, prices, nowSec: deps().nowSec(), maxRegistryAgeSec: MAX_ALLOWLIST_AGE_SEC };
}

/**
 * `emptyWallet`: the weights are valid but the wallet holds nothing yet. The target may still be saved (onboarding lets a
 * new user finish before funding); it is checked against real holdings again when a round builds the intent.
 */
export type TargetCheck = { ok: true; preview: GoalPreview; prices: ReadonlyMap<AssetUid, bigint> } | { ok: false; problems: string[]; emptyWallet?: true };

export const EMPTY_WALLET_NOTE = "This wallet holds no bStocks or USDT on BNB Chain yet. Your target is saved and applies as soon as the wallet holds an asset Sama trades.";

export async function checkTarget(address: Address, target: Omit<SavedTarget, "updatedAt">): Promise<TargetCheck> {
  const portfolio = await loadPortfolio(address);
  if (!portfolio.ok) return { ok: false, problems: [portfolio.detail] };
  if (portfolio.holdings.length === 0) return { ok: false, problems: [EMPTY_WALLET_NOTE], emptyWallet: true };
  const ctx = await resolveContext(portfolio);
  const result = resolveGoal(specFromTarget(target, portfolio.holdings.map((h) => h.asset.symbol)), ctx, policyFor(target, ctx.nowSec));
  return result.ok ? { ok: true, preview: result.preview, prices: ctx.prices } : { ok: false, problems: result.problems.map((p) => p.detail) };
}

/** The trades that would move the wallet to the target at current prices; moves under $1 are not shown. */
export function toWirePreview(check: TargetCheck): TargetPreview {
  // An empty wallet is not an error: the target is valid and can be saved; the note explains why there are no trades.
  if (!check.ok) return check.emptyWallet ? { ok: true, problems: check.problems, trades: [] } : { ok: false, problems: check.problems, trades: [] };
  const trades = check.preview.tokens
    .filter((t) => t.deltaUsdE18 !== 0n)
    .map((t) => {
      const value = t.deltaUsdE18 < 0n ? -t.deltaUsdE18 : t.deltaUsdE18;
      const price = check.prices.get(t.uid) ?? 0n;
      return { symbol: t.symbol, side: t.deltaUsdE18 < 0n ? ("SELL" as const) : ("BUY" as const), valueUsd: usd(value), amountTokens: price > 0n ? tokensOf((value * 10n ** 18n) / price) : 0 };
    })
    .filter((t) => t.valueUsd >= 1)
    .sort((a, b) => b.valueUsd - a.valueUsd);
  return { ok: true, problems: [], trades };
}

export function toWireTarget(t: SavedTarget): Target {
  return { weights: Object.fromEntries(t.weights.map((w) => [w.symbol, w.weightBps / 100])), costCapBps: t.costCapBps, residualStyle: t.residualStyle, savedAt: t.updatedAt };
}
